channels:
  local:
    variant: hub
    format: '&b[L] &7[%prefix%&7] &7%sender% &8&l> &e%message%'
  global:
    format: '%servercolor%[G] &7[%prefix%&7] &7%sender% &8&l> &f%message%'
  mb:
    format: '&7[&aMB&7] &7[&a%server%&7] &c%sender% &c&l> &a%message%'
  pm:
    format_to: '&3[to: %target%] &b%message%'
    format_from: '&3[from: %sender%] &b%message%'
  
redis:
  channel: rcdev
  host: localhost
  
storage:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: minecraft
    database: ruinscraft
