channels:
  local:
    enabled: true
    variant: hub
  global:
    enabled: true

redis:
  channel: rcdev
  host: localhost
  
storage:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: minecraft
    database: ruinscraft