channels:
  local:
    variant: hub
    format: '[L] [%prefix%] %username% > &e%message%'
    format_spy: '&7&o[L (%server%)] [%prefix%] %username% > %message%'
  global:
    format: '[G] [%prefix%] %username% > %message%'
  pm:
    format_to: '&3[to: %target%] &b%message%'
    format_from: '&3[from: %sender%] &b%message%'
  
redis:
  channel: rcdev
  host: localhost
  
storage:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: minecraft
    database: ruinscraft
