name: ${name}
version: ${version}
main: ${mainClass}

depend: [Vault]

softdepend: [PlotSquared]

commands:
  pm:
    aliases: [message, msg, m, whisper, whis, w, tell, t]
  ignore:
  channel:
  spy: